name: Release

on:
  push: {tags: ['v*']}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install bash-import
        run: |
          sudo curl -1fsSLR https://github.com/curatorium/bash-import/releases/latest/download/bash-import -o /usr/local/bin/bash-import;
          sudo chmod +x /usr/local/bin/bash-import;

      - name: Build release artifacts
        run: |
          bash-import pack bash-import -o .dist/bash-import
          bash-import pack bash-test -o .dist/bash-test
          cp .deps/*.sh .dist/

      - name: Run checks (shellcheck + tests)
        run: .githooks/pre-commit

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --title "${{ github.ref_name }}" --generate-notes --latest .dist/*
